# LLM deployment for documentation improvement
# Optimized for resource-constrained clusters

apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation-improver-llm
  namespace: doc-improver
  labels:
    app: documentation-improver-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentation-improver-llm
  template:
    metadata:
      labels:
        app: documentation-improver-llm
    spec:
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: llm
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
            - name: OLLAMA_ORIGINS
              value: "*"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: documentation-improver-llm-service
  namespace: doc-improver
  labels:
    app: documentation-improver-llm
spec:
  selector:
    app: documentation-improver-llm
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
