apiVersion: v1
kind: Namespace
metadata:
  name: doc-improver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation-improver-frontend
  namespace: doc-improver
  labels:
    app: documentation-improver-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentation-improver-frontend
  template:
    metadata:
      labels:
        app: documentation-improver-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: ghcr.io/niranec77/documentation-improver-documentation-improver-frontend:main-81bcfcb
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://documentation-improver-backend:5000"
            - name: REACT_APP_WS_URL
              value: "ws://documentation-improver-backend:5000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: documentation-improver-frontend-service
  namespace: doc-improver
  labels:
    app: documentation-improver-frontend
spec:
  selector:
    app: documentation-improver-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: documentation-improver-backend
  namespace: doc-improver
  labels:
    app: documentation-improver-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documentation-improver-backend
  template:
    metadata:
      labels:
        app: documentation-improver-backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: ghcr.io/niranec77/documentation-improver-documentation-improver-backend:main-81bcfcb
          ports:
            - containerPort: 5000
          env:
            - name: LLM_SERVICE_URL
              value: "http://localhost:11434"  # Fallback to local if LLM not available
            - name: MODEL_NAME
              value: "codellama:7b"
            - name: MAX_TOKENS
              value: "4096"
            - name: SECRET_KEY
              value: "your-secret-key-here"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: documentation-improver-backend-service
  namespace: doc-improver
  labels:
    app: documentation-improver-backend
spec:
  selector:
    app: documentation-improver-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
